#!/bin/bash

set -euo pipefail

pluginDir=".semrel/$(go env GOOS)_$(go env GOARCH)/files-updater-gradle/1.1.3/"
[[ ! -d "$pluginDir" ]] && {
  echo "creating $pluginDir"
  mkdir -p $pluginDir
}

go build -o $pluginDir/updater-gradle ./cmd/files-updater-gradle
